spring:
  application:
    name: demo-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9000/oauth2/jwks
logging:
  level:
    org.springframework.security: DEBUG
server:
  port: 9091
